FROM rust:1.96.0-bookworm AS rust-base

RUN rustup target add wasm32-unknown-unknown

FROM node:22-bookworm

ENV RUSTUP_HOME=/usr/local/rustup
ENV CARGO_HOME=/usr/local/cargo
ENV PATH=/usr/local/cargo/bin:${PATH}

COPY --from=rust-base /usr/local/cargo /usr/local/cargo
COPY --from=rust-base /usr/local/rustup /usr/local/rustup

WORKDIR /workspace
